//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace di.proyecto.clase.Modelo
{
    using di.proyecto.clase.MWM;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class incidencias: MVBase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public incidencias()
        {
            this.tiposhw = new HashSet<tiposhw>();
            this.tipossw = new HashSet<tipossw>();
        }
    
        public short idincidencias { get; set; }
        public Nullable<System.DateTime> Fecha_incidencia { get; set; }
        public Nullable<System.DateTime> Fecha_Introduccion { get; set; }
        public short Profesor_introduce { get; set; }
        public string Aula { get; set; }
        public string Descripcion { get; set; }
        public string Observaciones { get; set; }
        public short Estado { get; set; }
        public Nullable<short> Responsable { get; set; }
        public Nullable<System.DateTime> Fecha_Resolucion { get; set; }
        public string Tiempo { get; set; }
        public string Informacion_Extra { get; set; }
    
        [Required]
        public virtual estados estados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tiposhw> tiposhw { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tipossw> tipossw { get; set; }
        public virtual profesores profesores { get; set; }
        public virtual profesores profesores1 { get; set; }
    }
}
