//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace di.proyecto.clase.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class incidenciasEntities : DbContext
    {
        public incidenciasEntities()
            : base("name=incidenciasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<departamento> departamento { get; set; }
        public virtual DbSet<estados> estados { get; set; }
        public virtual DbSet<incidencias> incidencias { get; set; }
        public virtual DbSet<permisos> permisos { get; set; }
        public virtual DbSet<profesores> profesores { get; set; }
        public virtual DbSet<roles> roles { get; set; }
        public virtual DbSet<tiposhw> tiposhw { get; set; }
        public virtual DbSet<tipossw> tipossw { get; set; }
    }
}
