//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace di.proyecto.clase.Modelo
{
    using di.proyecto.clase.MWM;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class profesores:MVBase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public profesores()
        {
            this.incidencias = new HashSet<incidencias>();
            this.incidencias1 = new HashSet<incidencias>();
        }
    
        public short idProfesores { get; set; }
        [MinLength(9), Required (ErrorMessage ="longitud minima de  9 caracteres")  ]
        public string Dni { get; set; }
        [Required ]
        public string Nombre { get; set; }
        [Required ]
        public string Apellidos { get; set; }

        public short Departamento { get; set; }
        [EmailAddress (ErrorMessage ="Correo no valido")]
        public string Email { get; set; }
        [Required]
        public string Password { get; set; }
        public short Rol { get; set; }
        [Required]
        public string username { get; set; }
        [Required]
        public string Estado { get; set; }

        [Required (ErrorMessage ="Campo requerido")]
        public virtual departamento departamento1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<incidencias> incidencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<incidencias> incidencias1 { get; set; }
        [Required]
        public virtual roles roles { get; set; }
    }
}
