//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace di.proyecto.clase.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tiposhw
    {
        public short idTipos { get; set; }
        public string Tipo { get; set; }
        public string Numero_Serie { get; set; }
        public string Modelo { get; set; }
        public short idIncidencia { get; set; }
    
        public virtual incidencias incidencias { get; set; }
    }
}
